name: Publish
on:
    push:
        branches:
            - master
        tags:
            - '*'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
                  cache: npm
            - run: npm ci
            - run: npm test

    publish:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
                  cache: npm
                  registry-url: 'https://registry.npmjs.org/'
            - run: npm ci
            - run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: '${{ secrets.NPM_TOKEN }}'
